services:
    penalty_web:
        container_name: penalty_web
        image: nginx:alpine
        ports:
            - "8800:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - penalty_app
        networks:
            - penalty_network
    
    penalty_app:
        container_name: penalty_app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        depends_on:
            - penalty_db
        volumes:
            - ./:/var/www
        networks:
            - penalty_network
        ports:
            - "9050:9000"
    
    penalty_db:
        image: mysql
        container_name: penalty_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - penalty_database:/var/lib/mysql
        networks:
            - penalty_network
        expose:
            - 3344
networks:
    penalty_network:
        driver: bridge
volumes:
    penalty_database: